version: "3.8"
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: seu_usuario/meu-app:latest
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      # Atualize a URL de conexão para PostgreSQL
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
