version: "3.8"
services:
  app:
    build:
      context: ./api        # contexto apontando para a pasta onde está o Dockerfile
      dockerfile: Dockerfile
    image: seu_usuario/meu-app:latest
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@db:3306/$MYSQL_DATABASE
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
