
services:
  app:
    image: antoniolma/app:v1.0.1
    ports:
      - "8080:80"
    env_file: .env
    environment:
      # So coloquei o usuario, senha e db por que pediu
      - DATABASE_URL=postgresql://antoniolma_pedronas:senha_muito_segura_123@db:5432/db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    hostname: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=antoniolma_pedronas
      - POSTGRES_PASSWORD=senha_muito_segura_123
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antoniolma_pedronas -d db"]
      interval: 5s  
      timeout: 5s
      retries: 5
    

